# Generated by Django 2.2.1 on 2019-05-15 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarSubjectiveQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_percentage', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='api.SubjectiveQuestion')),
                ('similar_to_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to_question', to='api.SubjectiveQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='SimilarObjectiveQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_percentage', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='api.ObjectiveQuestion')),
                ('similar_to_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to_question', to='api.ObjectiveQuestion')),
            ],
        ),
    ]
