# Generated by Django 2.2.1 on 2019-05-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_objectivequestion_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activation',
        ),
    ]
