# Generated by Django 2.2.1 on 2019-05-15 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_similarobjectivequestions_similarsubjectivequestions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimilarObjectiveQuestions',
            new_name='SimilarObjectiveQuestion',
        ),
        migrations.RenameModel(
            old_name='SimilarSubjectiveQuestions',
            new_name='SimilarSubjectiveQuestion',
        ),
    ]
