# Generated by Django 2.2.1 on 2019-05-18 11:27

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190516_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='state',
            field=models.CharField(default='created', max_length=50),
        ),
        migrations.CreateModel(
            name='ArchievedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(default='NA', max_length=100)),
                ('question_html', models.TextField(default='NA')),
                ('solution_html', models.TextField(default='NA')),
                ('is_publish', models.CharField(default='NA', max_length=10)),
                ('is_active', models.CharField(default='NA', max_length=10)),
                ('tc_map_id', models.CharField(default='NA', max_length=100)),
                ('text_book_id', models.CharField(default='NA', max_length=100)),
                ('chapter_id', models.CharField(default='NA', max_length=100)),
                ('exercise_id', models.CharField(default='NA', max_length=100)),
                ('flow', models.CharField(default='NA', max_length=100)),
                ('set_no', models.CharField(default='NA', max_length=100)),
                ('page_flow', models.CharField(default='NA', max_length=100)),
                ('page_no', models.CharField(default='NA', max_length=100)),
                ('question_no', models.CharField(default='NA', max_length=100)),
                ('exercise_flow', models.CharField(default='NA', max_length=100)),
                ('edition', models.CharField(default='NA', max_length=100)),
                ('tc_map_is_active', models.CharField(default='', max_length=10)),
                ('slo_id', models.CharField(default='NA', max_length=100)),
                ('slo_map_id', models.CharField(default='NA', max_length=100)),
                ('slo_mao_is_active', models.CharField(default='', max_length=10)),
                ('exercise_name', models.CharField(default='NA', max_length=150)),
                ('question_level', models.IntegerField(default=0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Source')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Topic')),
            ],
        ),
    ]
