# Generated by Django 2.2.1 on 2019-05-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_activation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectivequestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='inquestion',
        ),
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='source',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='subjectivequestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
        migrations.DeleteModel(
            name='InQuestion',
        ),
        migrations.DeleteModel(
            name='ObjectiveQuestion',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.DeleteModel(
            name='Standard',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='SubjectiveQuestion',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
