# Generated by Django 2.2.1 on 2019-05-15 12:06

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20190515_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='InQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(default='NA', max_length=100)),
                ('question_html', models.TextField(default='NA')),
                ('solution_html', models.TextField(default='NA')),
                ('is_publish', models.CharField(default='NA', max_length=10)),
                ('is_active', models.CharField(default='NA', max_length=10)),
                ('tc_map_id', models.CharField(default='NA', max_length=100)),
                ('text_book_id', models.CharField(default='NA', max_length=100)),
                ('chapter_id', models.CharField(default='NA', max_length=100)),
                ('exercise_id', models.CharField(default='NA', max_length=100)),
                ('flow', models.CharField(default='NA', max_length=100)),
                ('set_no', models.CharField(default='NA', max_length=100)),
                ('page_flow', models.CharField(default='NA', max_length=100)),
                ('page_no', models.CharField(default='NA', max_length=100)),
                ('question_no', models.CharField(default='NA', max_length=100)),
                ('exercise_flow', models.CharField(default='NA', max_length=100)),
                ('edition', models.CharField(default='NA', max_length=100)),
                ('tc_map_is_active', models.CharField(default='', max_length=10)),
                ('slo_id', models.CharField(default='NA', max_length=100)),
                ('slo_map_id', models.CharField(default='NA', max_length=100)),
                ('slo_mao_is_active', models.CharField(default='', max_length=10)),
                ('exercise_name', models.CharField(default='NA', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='NA', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(default='imported', max_length=50)),
                ('level', models.IntegerField(default=0)),
                ('length', models.CharField(default='', max_length=25)),
                ('inquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.InQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=100)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Standard')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='', max_length=200)),
                ('topic_id', models.IntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectiveQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_html', models.CharField(default='', max_length=10000)),
                ('solution_html', models.CharField(default='', max_length=10000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(default='', max_length=100)),
                ('source_type', models.CharField(default='JSON file', max_length=100)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Standard')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Topic'),
        ),
        migrations.CreateModel(
            name='ObjectiveQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_html', models.CharField(default='', max_length=10000)),
                ('solution_html', models.CharField(default='', max_length=10000)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, size=None)),
                ('correct_option', models.CharField(max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Question')),
            ],
        ),
        migrations.AddField(
            model_name='inquestion',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Source'),
        ),
        migrations.AddField(
            model_name='inquestion',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Topic'),
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
