# Generated by Django 2.2.1 on 2019-05-18 13:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190518_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archievedquestion',
            name='question_html',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='archievedquestion',
            name='solution_html',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='inquestion',
            name='question_html',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='inquestion',
            name='solution_html',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='objectivequestion',
            name='question_html',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='objectivequestion',
            name='solution_html',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='question_html',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='solution_html',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
