# Generated by Django 2.2.1 on 2019-05-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190518_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectivequestion',
            name='correct_option',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
