# Generated by Django 2.2.1 on 2019-05-15 15:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_inquestion_question_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectivequestion',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
    ]
