# Generated by Django 2.2.1 on 2019-05-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190519_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='state',
            field=models.CharField(choices=[('created', 'created'), ('imported', 'imported'), ('duplicate', 'duplicate'), ('rejected', 'rejected')], default=('created', 'created'), max_length=100),
        ),
    ]
