# Generated by Django 2.2.1 on 2019-05-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190520_0209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
